repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,W503"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python3 -m pytest tests/unit -x -q --no-header --override-ini="addopts=-ra"
        language: system
        types: [python]
        pass_filenames: false
